(set-logic LIA)
(synth-fun next ((is_input Bool) (timer Int) ) Int
	((Start Int) (Var Int) (StartBool Bool))
	((Start Int (
				 0
				 1
				 (ite StartBool Start Start)))

	(Var Int (
			 5
			 timer
			 (+ Var Var)						
			 (- Var Var)						
			 (* Var Var)))

	(StartBool Bool (
				 	 is_input
					(= Var Var)						
					(>= Var Var)						
					(<= Var Var)						
					(and StartBool StartBool)			
					(or  StartBool StartBool)				
					(not StartBool)))))

(constraint (= (next false 0 ) 0))
(constraint (= (next false 1 ) 0))
(constraint (= (next false 2 ) 0))
(constraint (= (next false 3 ) 0))
(constraint (= (next false 4 ) 0))
(constraint (= (next false 5 ) 1))
(constraint (= (next true 6 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next false 0 ) 0))
(constraint (= (next false 1 ) 0))
(constraint (= (next false 2 ) 0))
(constraint (= (next false 3 ) 0))
(constraint (= (next false 4 ) 0))
(constraint (= (next false 5 ) 1))
(constraint (= (next true 6 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))
(constraint (= (next true 0 ) 0))

(check-synth)
